ServerName localhost

<Directory /var/www/html>
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
</Directory>

<Directory /var/www/storage>
    AllowOverride None
    Options -Indexes
    Require all denied
</Directory>
